services:
  python_app:
    image: python:3.10.13-alpine3.19
    container_name: discordBot
    restart: always
    networks:
      - conexionBot
    volumes:
      - ../python/src:/usr/src/app
    environment:
      - PIP_ROOT_USER_ACTION=ignore
    command: sh /usr/src/app/entrypoint.sh

  mysql_db:
    image: mysql:8.0.35-debian
    container_name: BaseDatosBot
    restart: always
    networks:
      - conexionBot
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ../mysql/data:/var/lib/mysql  
      - ../mysql/initSQL.sql:/docker-entrypoint-initdb.d/initSQL.sql  
    ports:
      - "3307:3306" 
    cap_add:
      - SYS_NICE
networks:
  conexionBot:
    driver: bridge
